databases:
  - name: hillwood_backend_dashboard_db
    databaseName: hillwood_backend_dashboard_development  # Use the correct development database name
    user: hillwood_backend_dashboard
    plan: free

services:
  - type: web
    name: hillwood_backend_dashboard
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hillwood_backend_dashboard_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
