
ROLE_NAMES = %i[user subscriber admin].freeze

DEFAUT_MOVIE_GENRES = [
  'Action',
  'Anime',
  'Classique',
  'Comedies',
  'Documenttaires',
  'Drames',
  'Horror',
  'Romance',
  'Crime',
  'African',
  'Science fiction',
]

 DEFAUT_GENRES_OF_MUSIC = [
    'Classical',
    'Love',
    'Religious',
    'Rock',
    'Instrumental'
  ]

  VIDEOS_MOVIES = [
    {
      url: 'https://www.youtube.com/watch?v=1Vnghdsjmd0',
      title: 'The Matrix',
      status: 1,
      details: {
        duration: '2h 16m',
        dimention: '2D',
        definition: 'HD',
        caption: 'English',
        mime_type: 'video/mp4'
      }
    },
    {
      url: 'https://www.youtube.com/watch?v=2X9E9kcf53g',
      title: 'Inception',
      status: 1,
      details: {
        duration: '2h 28m',
        dimention: '2D',
        definition: 'HD',
        caption: 'English',
        mime_type: 'video/mp4'
      }
    },
    {
      url: 'https://www.youtube.com/watch?v=j9HivyjAKlc',
      title: 'The Shawshank Redemption',
      status: 1,
      details: {
        duration: '2h 22m',
        dimention: '2D',
        definition: 'HD',
        caption: 'English',
        mime_type: 'video/mp4'
      }
    },
    {
      url: 'https://www.youtube.com/watch?v=6hB3S9bIaco',
      title: 'Interstellar',
      status: 1,
      details: {
        duration: '2h 49m',
        dimention: '2D',
        definition: 'HD',
        caption: 'English',
        mime_type: 'video/mp4'
      }
    },
    {
      url: 'https://www.youtube.com/watch?v=OTfB_DnFO2Y',
      title: 'The Dark Knight',
      status: 1,
      details: {
        duration: '2h 32m',
        dimention: '2D',
        definition: 'HD',
        caption: 'English',
        mime_type: 'video/mp4'
      }
    },
    {
      url: 'https://www.youtube.com/watch?v=yzy6Xs78WM0',
      title: 'Fight Club',
      status: 1,
      details: {
        duration: '2h 19m',
        dimention: '2D',
        definition: 'HD',
        caption: 'English',
        mime_type: 'video/mp4'
      }
    }
  ].freeze
  

INTERESTS = [
  {
    id: 1,
    name: 'Agriculture',
    icon: 'https://i.ibb.co/2h76Ds5/agriculture.png',
    sub_interests: [
      'Animal Husbandry',
      'Agricultural Extension and Rural Development',
      'Agricultural Economics',
      'Agricultural Engineering',
      'Agricultural Microbiology',
      'Agronomy',
      'Animal Sciences',
      'Crop Production and Protection',
      'Entomology',
      'Environmental Sciences',
      'Family, Nutrition & Consumer Sciences',
      'Food Science and Technology',
      'Forestry',
      'Genetics and plant breeding',
      'Horticulture',
      'Land and Water Management',
      'Plant Protection',
      'Plant Psychology',
      'Plant Science',
      'Soil Science and Soil Chemistry',
    ],
  },
  {
    id: 2,
    name: 'Real estate',
    icon: 'https://i.ibb.co/yPCvsy4/RE-1.png',
    sub_interests: [
      'Commercial',
      'Industrial',
      'Raw land',
      'Residential',
      'Special use',
    ],
  },
  {
    id: 3,
    name: 'Food & drinks',
    icon: 'https://i.ibb.co/6svTTD0/soda.png',
    sub_interests: [
      'Beverage - water, alcoholic drinks, fruit drinks, soda, juice',
      'Dairy',
      'Fast Food',
      'Fruits and Vegetables',
      'Grain',
      'Herbs and Spices',
      'Meat, Poultry, and seafood',
      'Sugar and Confectionery',
    ],
  },
  {
    id: 4,
    name: 'Healthcare',
    icon: 'https://i.ibb.co/BrhpjhN/healthcare.png',
    sub_interests: [
      'Ambulatory services',
      'Dental care',
      'Family Planning & Abortion Clinics',
      'Laboratory and diagnostic care',
      'Manufacturer of medical devices, equipment, and hospital supplies',
      'Medical Insurance',
      'Mental health care',
      'Nutritional support',
      'Pathology',
      'Physical and occupational therapy',
      'Pharmaceutical care',
      'Pharmaceuticals and related segments',
      'Prenatal care',
      'Preventative care',
      'Substance abuse treatment',
    ],
  },
  {
    id: 5,
    name: 'Hospitality',
    icon: 'https://i.ibb.co/XJz9g7s/hospitality.png',
    sub_interests: [
      'Accommodation',
      'Attractions',
      'Entertainment and Recreation',
      'Meetings and Events',
      'Travel and Tourism',
    ],
  },
  {
    id: 6,
    name: 'Creative',
    icon: 'https://i.ibb.co/d6LtM6N/creativity.png',
    sub_interests: [
      'Acting',
      'Advertising and Marketing',
      'Architecture',
      'Arts and Design',
      'Crafts',
      'Electronic Publishing',
      'Film',
      'Graphic Design',
      'Journalism',
      'Museums and Libraries',
      'Music',
      'Performing Arts',
      'Photography',
      'Technical Writing',
      'TV and Radio, including Broadcast production',
      'Video',
    ],
  },
  {
    id: 7,
    name: 'IT',
    icon: 'https://i.ibb.co/W5Mwjcm/it.png',
    sub_interests: [
      '3D modelling software',
      'Animation',
      'API design software',
      'API management tools',
      'Access gateway',
      'Artificial Intelligence',
      'Cloud Computing',
      'Computer Games',
      'Computer Graphics',
      'Data Science',
      'Hardware Engineering',
      'Network Administration',
      'Object-Oriented Programming',
      'Operating Systems',
      'Quality Assurance',
      'Software Engineering',
      'Telecommunications',
      'User Experience Design',
      'Security Specialist',
    ],
  },
  {
    id: 8,
    name: 'Financial services',
    icon: 'https://i.ibb.co/SJGnjWv/business.png',
    sub_interests: [
      'Accounting',
      'Advisory',
      'Business banking',
      'Funds and investment',
      'Insurance',
      'Investment banking',
      'Life assurance and pensions',
      'Regulated advice',
      'Retail banking',
    ],
  },
  {
    id: 9,
    name: 'Education',
    icon: 'https://i.ibb.co/JvmtLFC/education.png',
    sub_interests: [
      'Assessment services',
      'Business schools',
      'It/computing schools',
      'Learning centres',
      'Special Needs',
      'Trade/vocational schools',
      'Tutoring services',
    ],
  },
  {
    id: 10,
    name: 'Oil & gas',
    icon: 'https://i.ibb.co/LR7xnmM/oil-and-gas.png',
    sub_interests: [
      'Downstream,which includes refining and marketing',
      'Midstream,transportation and storage',
      'Upstream,the business of oil and gas exploration and production',
    ],
  },
  {
    id: 11,
    name: 'Ecosystems & Environment',
    icon: 'https://i.ibb.co/7g1bj8B/environment.png',
    sub_interests: [
      'Startups',
      'Programs',
      'Investors',
      'Co-working Spaces',
      'Accelerators',
      'Incubators',
      'Startup Consulting',
      'Recruitment Agencies',
      'Grant Institutions',
      'NGOs',
      'Companies',
      'Desert ecosystems',
      'Forest ecosystems',
      'Freshwater ecosystems',
      'Grassland ecosystem',
      'Marine ecosystems',
      'Tundra ecosystems',
    ],
  },
  {
    id: 12,
    name: 'Construction',
    icon: 'https://i.ibb.co/kM2Zd3g/construction.png',
    sub_interests: [
      'Infrastructure and Heavy Construction',
      'Institutional and Commercial Building',
      'Residential Building',
      'Specialized industrial construction',
    ],
  },
  {
    id: 13,
    name: 'Manufacturing',
    icon: 'https://i.ibb.co/pf0MYJY/manufacture.png',
    sub_interests: [
      'Clothing and textiles',
      'Electronic,computers and transportation',
      'Food production',
      'Metal manufacturing',
      'Petroleum ,chemicals and plastics',
      'Wood, leather and paper',
    ],
  },
  {
    id: 14,
    name: 'Transportation',
    icon: 'https://i.ibb.co/0Z5dwXh/trucking.png',
    sub_interests: [
      'Air Transport',
      'Boats',
      'Car Hire',
      'Cargo',
      'Livestock Transportation',
      'Marine Shipping',
      'Medical Transport',
      'Senior Services',
      'Specialty Transportation',
      'Taxi Service',
    ],
  },
  {
    id: 15,
    name: 'Utilities',
    icon: 'https://i.ibb.co/WctjVzt/house.png',
    sub_interests: [
      'Electricity',
      'Garbage Disposal',
      'Gas',
      'Water/ Sewage',
    ],
  },
  {
    id: 16,
    name: 'Energy And Metals',
    icon: 'https://i.ibb.co/m8sCgVB/precious-stone.png',
    sub_interests: [
      'Chemical',
      'Electrical',
      'Ferrous',
      'Mechanical',
      'Non Ferrous metals and alloys',
      'Radiant',
      'Thermal and Nuclear',
    ],
  },
  {
    id: 17,
    name: 'Fashion and Wellbeing',
    icon: 'https://i.ibb.co/m66Xjtd/Whats-App-Image-2022-04-06-at-17-50-05.jpg',
    sub_interests: [
      'Accessories',
      'Buyers',
      'Costume',
      'Designer',
      'Editorial',
      'Fabric',
      'Fitting ',
      'Hair',
      'Makeup',
      'Model',
      'Nails',
      'Patterns',
      'Production',
      'Stylist',
      'Tailor',
      'Textiles',
    ],
  },
  {
    id: 18,
    name: 'Sports',
    icon: 'https://i.ibb.co/kygb7dZ/sport.png',
    sub_interests: [
      'Archery',
      'Athletics',
      'Basketball',
      'Boxing',
      'Fencing',
      'Football',
      'Golfers',
      'Gymnastics',
      'Ice Hockey',
      'Tennis',
      'Pool',
      'Rugby',
      'Volleyball',
    ],
  },
  {
    id: 19,
    name: 'Entertainment',
    icon: 'https://i.ibb.co/kygb7dZ/sport.png',
    sub_interests: [
      'Action',
      'Adventure fiction',
      'Amusement park',
      'Animation',
      'Art',
      'Circus',
      'Comedy',
      'Comedy club',
      'Concert',
      'Dance',
      'Drama',
      'Humour',
      'Museum',
      'Music',
      'Musical theatre',
      'Nightclub',
      'Performing arts',
      'Radio',
      'Sports',
      'Theatre',
    ],
  },
  {
    id: 20,
    name: 'Social Media',
    icon: 'https://i.ibb.co/kygb7dZ/sport.png',
    sub_interests: [
      'Action',
      'Adventure fiction',
      'Amusement park',
      'Animation',
      'Art',
      'Circus',
      'Comedy',
      'Comedy club',
      'Concert',
      'Dance',
      'Drama',
      'Humour',
      'Museum',
      'Music',
      'Musical theatre',
      'Nightclub',
      'Performing arts',
      'Radio',
      'Sports',
      'Theatre',
    ],
  },
].freeze

